#
# This file generated by build/perl/mvs38j-genall and build/perl/mvs38j-geninc
# from specifications in build/macros.mk
# Constructed via compile/Makefile
#
# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arp
ARP = arp/arp_in.c	arp/arpadd.c	 \
	arp/arpalloc.c	arp/arpdq.c	 \
	arp/arpdump.c	arp/arpfind.c	 \
	arp/arpinit.c	arp/arpprint.c	 \
	arp/arpqsend.c	arp/arpsend.c	 \
	arp/arptimer.c	arp/mkarp.c	 \
	arp/rarp_in.c	arp/rarpsend.c	 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arp
ARPOBJ = ../build/obj/arp_in.xsd	../build/obj/arpadd.xsd	 \
	../build/obj/arpalloc.xsd	../build/obj/arpdq.xsd	 \
	../build/obj/arpdump.xsd	../build/obj/arpfind.xsd	 \
	../build/obj/arpinit.xsd	../build/obj/arpprint.xsd	 \
	../build/obj/arpqsend.xsd	../build/obj/arpsend.xsd	 \
	../build/obj/arptimer.xsd	../build/obj/mkarp.xsd	 \
	../build/obj/rarp_in.xsd	../build/obj/rarpsend.xsd	 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/com
COM = 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/com
COMOBJ = 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/debug
DEBUG = debug/hexdump.c	debug/ospfdump.c	 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/debug
DEBUGOBJ = ../build/obj/hexdump.xsd	../build/obj/ospfdump.xsd	 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/dgram
DGRAM = dgram/dgalloc.c	dgram/dgclose.c	 \
	dgram/dgcntl.c	dgram/dgdump.c	 \
	dgram/dginit.c	dgram/dgmcntl.c	 \
	dgram/dgmopen.c	dgram/dgread.c	 \
	dgram/dgwrite.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/dgram
DGRAMOBJ = ../build/obj/dgalloc.xsd	../build/obj/dgclose.xsd	 \
	../build/obj/dgcntl.xsd	../build/obj/dgdump.xsd	 \
	../build/obj/dginit.xsd	../build/obj/dgmcntl.xsd	 \
	../build/obj/dgmopen.xsd	../build/obj/dgread.xsd	 \
	../build/obj/dgwrite.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/ether
ETHER = 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/ether
ETHEROBJ = 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/icmp
ICMP = icmp/icerrok.c	icmp/icmp.c	 \
	icmp/icmp_in.c	icmp/icmpdump.c	 \
	icmp/icredirect.c	icmp/icsetbuf.c	 \
	icmp/icsetdata.c	icmp/icsetsrc.c	 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/icmp
ICMPOBJ = ../build/obj/icerrok.xsd	../build/obj/icmp.xsd	 \
	../build/obj/icmp_in.xsd	../build/obj/icmpdump.xsd	 \
	../build/obj/icredirect.xsd	../build/obj/icsetbuf.xsd	 \
	../build/obj/icsetdata.xsd	../build/obj/icsetsrc.xsd	 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/igmp
IGMP = igmp/hgadd.c	igmp/hgarpadd.c	 \
	igmp/hgarpdel.c	igmp/hginit.c	 \
	igmp/hgjoin.c	igmp/hgleave.c	 \
	igmp/hglookup.c	igmp/hgprint.c	 \
	igmp/hgrand.c	igmp/igmp.c	 \
	igmp/igmp_in.c	igmp/igmp_settimers.c	 \
	igmp/igmp_update.c	igmp/igmpdump.c	 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/igmp
IGMPOBJ = ../build/obj/hgadd.xsd	../build/obj/hgarpadd.xsd	 \
	../build/obj/hgarpdel.xsd	../build/obj/hginit.xsd	 \
	../build/obj/hgjoin.xsd	../build/obj/hgleave.xsd	 \
	../build/obj/hglookup.xsd	../build/obj/hgprint.xsd	 \
	../build/obj/hgrand.xsd	../build/obj/igmp.xsd	 \
	../build/obj/igmp_in.xsd	../build/obj/igmp_settimers.xsd	 \
	../build/obj/igmp_update.xsd	../build/obj/igmpdump.xsd	 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/ip
IP = ip/ip_in.c	ip/ipcksum.c	 \
	ip/ipdbc.c	ip/ipdoopts.c	 \
	ip/ipdstopts.c	ip/ipdump.c	 \
	ip/ipfadd.c	ip/ipfcons.c	 \
	ip/ipfhcopy.c	ip/ipfinit.c	 \
	ip/ipfjoin.c	ip/ipfsend.c	 \
	ip/ipftimer.c	ip/ipgetp.c	 \
	ip/iph2net.c	ip/ipnet2h.c	 \
	ip/ipproc.c	ip/ipputp.c	 \
	ip/ipreass.c	ip/ipredirect.c	 \
	ip/ipsend.c	ip/ipshowhdr.c	 \
	ip/isbrc.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/ip
IPOBJ = ../build/obj/ip_in.xsd	../build/obj/ipcksum.xsd	 \
	../build/obj/ipdbc.xsd	../build/obj/ipdoopts.xsd	 \
	../build/obj/ipdstopts.xsd	../build/obj/ipdump.xsd	 \
	../build/obj/ipfadd.xsd	../build/obj/ipfcons.xsd	 \
	../build/obj/ipfhcopy.xsd	../build/obj/ipfinit.xsd	 \
	../build/obj/ipfjoin.xsd	../build/obj/ipfsend.xsd	 \
	../build/obj/ipftimer.xsd	../build/obj/ipgetp.xsd	 \
	../build/obj/iph2net.xsd	../build/obj/ipnet2h.xsd	 \
	../build/obj/ipproc.xsd	../build/obj/ipputp.xsd	 \
	../build/obj/ipreass.xsd	../build/obj/ipredirect.xsd	 \
	../build/obj/ipsend.xsd	../build/obj/ipshowhdr.xsd	 \
	../build/obj/isbrc.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/kbm
KBM = 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/kbm
KBMOBJ = 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/lib
LIB = lib/bzero.c	lib/doscan.c	 \
	lib/ecvt.c	lib/swab.c	 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/lib
LIBOBJ = ../build/obj/bzero.xsd	../build/obj/doscan.xsd	 \
	../build/obj/ecvt.xsd	../build/obj/swab.xsd	 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/net
NET = net/getiaddr.c	net/getname.c	 \
	net/gname.c	net/initgate.c	 \
	net/inithost.c	net/local_out.c	 \
	net/name2ip.c	net/netproc.c	 \
	net/netstart.c	net/netup_gath.c	 \
	net/netup_nif.c	net/netup_rt.c	 \
	net/netwrite.c	net/ni_in.c	 \
	net/resolve.c	net/slowtimer.c	 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/net
NETOBJ = ../build/obj/getiaddr.xsd	../build/obj/getname.xsd	 \
	../build/obj/gname.xsd	../build/obj/initgate.xsd	 \
	../build/obj/inithost.xsd	../build/obj/local_out.xsd	 \
	../build/obj/name2ip.xsd	../build/obj/netproc.xsd	 \
	../build/obj/netstart.xsd	../build/obj/netup_gath.xsd	 \
	../build/obj/netup_nif.xsd	../build/obj/netup_rt.xsd	 \
	../build/obj/netwrite.xsd	../build/obj/ni_in.xsd	 \
	../build/obj/resolve.xsd	../build/obj/slowtimer.xsd	 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/netapp
NETAPP = netapp/echod.c	netapp/egp.c	 \
	netapp/fingerd.c	netapp/lfing.c	 \
	netapp/rwho.c	netapp/rwhod.c	 \
	netapp/rwhoind.c	netapp/snmpd.c	 \
	netapp/udpecho.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/netapp
NETAPPOBJ = ../build/obj/echod.xsd	../build/obj/egp.xsd	 \
	../build/obj/fingerd.xsd	../build/obj/lfing.xsd	 \
	../build/obj/rwho.xsd	../build/obj/rwhod.xsd	 \
	../build/obj/rwhoind.xsd	../build/obj/snmpd.xsd	 \
	../build/obj/udpecho.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/netutil
NETUTIL = netutil/cksum.c	netutil/dnparse.c	 \
	netutil/dot2ip.c	netutil/getnet.c	 \
	netutil/hwa2string.c	netutil/ip2dot.c	 \
	netutil/ip2name.c	netutil/netdump.c	 \
	netutil/netmask.c	netutil/netmatch.c	 \
	netutil/netnum.c	netutil/nifdump.c	 \
	netutil/strlower.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/netutil
NETUTILOBJ = ../build/obj/cksum.xsd	../build/obj/dnparse.xsd	 \
	../build/obj/dot2ip.xsd	../build/obj/getnet.xsd	 \
	../build/obj/hwa2string.xsd	../build/obj/ip2dot.xsd	 \
	../build/obj/ip2name.xsd	../build/obj/netdump.xsd	 \
	../build/obj/netmask.xsd	../build/obj/netmatch.xsd	 \
	../build/obj/netnum.xsd	../build/obj/nifdump.xsd	 \
	../build/obj/strlower.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/ospf
OSPF = 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/ospf
OSPFOBJ = 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/rfs
RFS = 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/rfs
RFSOBJ = 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/rip
RIP = rip/ripadd.c	rip/ripcheck.c	 \
	rip/ripifset.c	rip/ripin.c	 \
	rip/ripmetric.c	rip/ripok.c	 \
	rip/ripout.c	rip/riprecv.c	 \
	rip/riprepl.c	rip/ripsend.c	 \
	rip/ripstart.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/rip
RIPOBJ = ../build/obj/ripadd.xsd	../build/obj/ripcheck.xsd	 \
	../build/obj/ripifset.xsd	../build/obj/ripin.xsd	 \
	../build/obj/ripmetric.xsd	../build/obj/ripok.xsd	 \
	../build/obj/ripout.xsd	../build/obj/riprecv.xsd	 \
	../build/obj/riprepl.xsd	../build/obj/ripsend.xsd	 \
	../build/obj/ripstart.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/route
ROUTE = route/rtadd.c	route/rtdel.c	 \
	route/rtdump.c	route/rtfree.c	 \
	route/rtget.c	route/rthash.c	 \
	route/rtinit.c	route/rtnew.c	 \
	route/rtprint.c	route/rttimer.c	 \
	route/setmask.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/route
ROUTEOBJ = ../build/obj/rtadd.xsd	../build/obj/rtdel.xsd	 \
	../build/obj/rtdump.xsd	../build/obj/rtfree.xsd	 \
	../build/obj/rtget.xsd	../build/obj/rthash.xsd	 \
	../build/obj/rtinit.xsd	../build/obj/rtnew.xsd	 \
	../build/obj/rtprint.xsd	../build/obj/rttimer.xsd	 \
	../build/obj/setmask.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/snmp
SNMP = 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/snmp
SNMPOBJ = 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/sys
SYS = 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/sys
SYSOBJ = 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/tcp
TCP = tcp/tcp_in.c	tcp/tcpabort.c	 \
	tcp/tcpacked.c	tcp/tcpackit.c	 \
	tcp/tcpcksum.c	tcp/tcpclosed.c	 \
	tcp/tcpclosewait.c	tcp/tcpclosing.c	 \
	tcp/tcpdata.c	tcp/tcpdemux.c	 \
	tcp/tcpdodat.c	tcp/tcpdump.c	 \
	tcp/tcpestablished.c	tcp/tcpfin1.c	 \
	tcp/tcpfin2.c	tcp/tcph2net.c	 \
	tcp/tcphowmuch.c	tcp/tcpidle.c	 \
	tcp/tcpinp.c	tcp/tcpiss.c	 \
	tcp/tcpkick.c	tcp/tcpkilltimers.c	 \
	tcp/tcplastack.c	tcp/tcplisten.c	 \
	tcp/tcpnet2h.c	tcp/tcpok.c	 \
	tcp/tcpopts.c	tcp/tcpostate.c	 \
	tcp/tcpout.c	tcp/tcppersist.c	 \
	tcp/tcpreset.c	tcp/tcprexmt.c	 \
	tcp/tcprmss.c	tcp/tcprtt.c	 \
	tcp/tcprwindow.c	tcp/tcpsend.c	 \
	tcp/tcpsmss.c	tcp/tcpsndlen.c	 \
	tcp/tcpswindow.c	tcp/tcpswitch.c	 \
	tcp/tcpsync.c	tcp/tcpsynrcvd.c	 \
	tcp/tcpsynsent.c	tcp/tcptimer.c	 \
	tcp/tcptimewait.c	tcp/tcpwait.c	 \
	tcp/tcpwakeup.c	tcp/tcpwinit.c	 \
	tcp/tcpxmit.c	tcp/tfcoalesce.c	 \
	tcp/tfinsert.c	tcp/tmclear.c	 \
	tcp/tmleft.c	tcp/tmset.c	 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/tcp
TCPOBJ = ../build/obj/tcp_in.xsd	../build/obj/tcpabort.xsd	 \
	../build/obj/tcpacked.xsd	../build/obj/tcpackit.xsd	 \
	../build/obj/tcpcksum.xsd	../build/obj/tcpclosed.xsd	 \
	../build/obj/tcpclosewait.xsd	../build/obj/tcpclosing.xsd	 \
	../build/obj/tcpdata.xsd	../build/obj/tcpdemux.xsd	 \
	../build/obj/tcpdodat.xsd	../build/obj/tcpdump.xsd	 \
	../build/obj/tcpestablished.xsd	../build/obj/tcpfin1.xsd	 \
	../build/obj/tcpfin2.xsd	../build/obj/tcph2net.xsd	 \
	../build/obj/tcphowmuch.xsd	../build/obj/tcpidle.xsd	 \
	../build/obj/tcpinp.xsd	../build/obj/tcpiss.xsd	 \
	../build/obj/tcpkick.xsd	../build/obj/tcpkilltimers.xsd	 \
	../build/obj/tcplastack.xsd	../build/obj/tcplisten.xsd	 \
	../build/obj/tcpnet2h.xsd	../build/obj/tcpok.xsd	 \
	../build/obj/tcpopts.xsd	../build/obj/tcpostate.xsd	 \
	../build/obj/tcpout.xsd	../build/obj/tcppersist.xsd	 \
	../build/obj/tcpreset.xsd	../build/obj/tcprexmt.xsd	 \
	../build/obj/tcprmss.xsd	../build/obj/tcprtt.xsd	 \
	../build/obj/tcprwindow.xsd	../build/obj/tcpsend.xsd	 \
	../build/obj/tcpsmss.xsd	../build/obj/tcpsndlen.xsd	 \
	../build/obj/tcpswindow.xsd	../build/obj/tcpswitch.xsd	 \
	../build/obj/tcpsync.xsd	../build/obj/tcpsynrcvd.xsd	 \
	../build/obj/tcpsynsent.xsd	../build/obj/tcptimer.xsd	 \
	../build/obj/tcptimewait.xsd	../build/obj/tcpwait.xsd	 \
	../build/obj/tcpwakeup.xsd	../build/obj/tcpwinit.xsd	 \
	../build/obj/tcpxmit.xsd	../build/obj/tfcoalesce.xsd	 \
	../build/obj/tfinsert.xsd	../build/obj/tmclear.xsd	 \
	../build/obj/tmleft.xsd	../build/obj/tmset.xsd	 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/tcpd
TCPD = tcpd/tcballoc.c	tcpd/tcbdealloc.c	 \
	tcpd/tcpbind.c	tcpd/tcpclose.c	 \
	tcpd/tcpcntl.c	tcpd/tcpcon.c	 \
	tcpd/tcpgetc.c	tcpd/tcpgetdata.c	 \
	tcpd/tcpgetspace.c	tcpd/tcpinit.c	 \
	tcpd/tcplq.c	tcpd/tcpmcntl.c	 \
	tcpd/tcpmopen.c	tcpd/tcpnxtp.c	 \
	tcpd/tcpputc.c	tcpd/tcpread.c	 \
	tcpd/tcpserver.c	tcpd/tcpstat.c	 \
	tcpd/tcpuopt.c	tcpd/tcpwr.c	 \
	tcpd/tcpwrite.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/tcpd
TCPDOBJ = ../build/obj/tcballoc.xsd	../build/obj/tcbdealloc.xsd	 \
	../build/obj/tcpbind.xsd	../build/obj/tcpclose.xsd	 \
	../build/obj/tcpcntl.xsd	../build/obj/tcpcon.xsd	 \
	../build/obj/tcpgetc.xsd	../build/obj/tcpgetdata.xsd	 \
	../build/obj/tcpgetspace.xsd	../build/obj/tcpinit.xsd	 \
	../build/obj/tcplq.xsd	../build/obj/tcpmcntl.xsd	 \
	../build/obj/tcpmopen.xsd	../build/obj/tcpnxtp.xsd	 \
	../build/obj/tcpputc.xsd	../build/obj/tcpread.xsd	 \
	../build/obj/tcpserver.xsd	../build/obj/tcpstat.xsd	 \
	../build/obj/tcpuopt.xsd	../build/obj/tcpwr.xsd	 \
	../build/obj/tcpwrite.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/tty
TTY = 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/tty
TTYOBJ = 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/udp
UDP = udp/udp_in.c	udp/udpcksum.c	 \
	udp/udpdump.c	udp/udph2net.c	 \
	udp/udpinit.c	udp/udpnet2h.c	 \
	udp/udpnxtp.c	udp/udpsend.c	 \
	udp/upalloc.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/udp
UDPOBJ = ../build/obj/udp_in.xsd	../build/obj/udpcksum.xsd	 \
	../build/obj/udpdump.xsd	../build/obj/udph2net.xsd	 \
	../build/obj/udpinit.xsd	../build/obj/udpnet2h.xsd	 \
	../build/obj/udpnxtp.xsd	../build/obj/udpsend.xsd	 \
	../build/obj/upalloc.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/user
USER = user/conf.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/user
USEROBJ = ../build/obj/conf.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/clock
CLOCK = arch/s370/clock/clkinit.c	arch/s370/clock/clkint.c	 \
	arch/s370/clock/clockstate.c	arch/s370/clock/gettime.c	 \
	arch/s370/clock/getutim.c	arch/s370/clock/insertd.c	 \
	arch/s370/clock/sleep.c	arch/s370/clock/sleep10.c	 \
	arch/s370/clock/sleep100.c	arch/s370/clock/stopclk.c	 \
	arch/s370/clock/strtclk.c	arch/s370/clock/unsleep.c	 \
	arch/s370/clock/wakeup.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/clock
CLOCKOBJ = ../build/obj/clkinit.xsd	../build/obj/clkint.xsd	 \
	../build/obj/clockstate.xsd	../build/obj/gettime.xsd	 \
	../build/obj/getutim.xsd	../build/obj/insertd.xsd	 \
	../build/obj/sleep.xsd	../build/obj/sleep10.xsd	 \
	../build/obj/sleep100.xsd	../build/obj/stopclk.xsd	 \
	../build/obj/strtclk.xsd	../build/obj/unsleep.xsd	 \
	../build/obj/wakeup.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/console
CONSOLE = arch/s370/console/mvsconswrite.c	arch/s370/console/oprconsiin.c	 \
	arch/s370/console/oprconsoin.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/console
CONSOLEOBJ = ../build/obj/mvsconswrite.xsd	../build/obj/oprconsiin.xsd	 \
	../build/obj/oprconsoin.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/ctc
CTC = arch/s370/ctc/ctci_init.c	arch/s370/ctc/ctci_ioread.c	 \
	arch/s370/ctc/ctci_iowrite.c	arch/s370/ctc/ctci_read.c	 \
	arch/s370/ctc/ctci_write.c	arch/s370/ctc/ctcpostread.c	 \
	arch/s370/ctc/ctcpostwrite.c	arch/s370/ctc/initutdev.c	 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/ctc
CTCOBJ = ../build/obj/ctci_init.xsd	../build/obj/ctci_ioread.xsd	 \
	../build/obj/ctci_iowrite.xsd	../build/obj/ctci_read.xsd	 \
	../build/obj/ctci_write.xsd	../build/obj/ctcpostread.xsd	 \
	../build/obj/ctcpostwrite.xsd	../build/obj/initutdev.xsd	 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/device
DEVICE = arch/s370/device/ioerr.c	arch/s370/device/iohook.c	 \
	arch/s370/device/ionull.c	arch/s370/device/noclose.c	 \
	arch/s370/device/nocntl.c	arch/s370/device/nogetc.c	 \
	arch/s370/device/noiint.c	arch/s370/device/nooint.c	 \
	arch/s370/device/noopen.c	arch/s370/device/noputc.c	 \
	arch/s370/device/noread.c	arch/s370/device/noseek.c	 \
	arch/s370/device/nowrite.c	arch/s370/device/xdevclose.c	 \
	arch/s370/device/xdevcontrol.c	arch/s370/device/xdevgetc.c	 \
	arch/s370/device/xdevinit.c	arch/s370/device/xdevopen.c	 \
	arch/s370/device/xdevputc.c	arch/s370/device/xdevread.c	 \
	arch/s370/device/xdevseek.c	arch/s370/device/xdevwrite.c	 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/device
DEVICEOBJ = ../build/obj/ioerr.xsd	../build/obj/iohook.xsd	 \
	../build/obj/ionull.xsd	../build/obj/noclose.xsd	 \
	../build/obj/nocntl.xsd	../build/obj/nogetc.xsd	 \
	../build/obj/noiint.xsd	../build/obj/nooint.xsd	 \
	../build/obj/noopen.xsd	../build/obj/noputc.xsd	 \
	../build/obj/noread.xsd	../build/obj/noseek.xsd	 \
	../build/obj/nowrite.xsd	../build/obj/xdevclose.xsd	 \
	../build/obj/xdevcontrol.xsd	../build/obj/xdevgetc.xsd	 \
	../build/obj/xdevinit.xsd	../build/obj/xdevopen.xsd	 \
	../build/obj/xdevputc.xsd	../build/obj/xdevread.xsd	 \
	../build/obj/xdevseek.xsd	../build/obj/xdevwrite.xsd	 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/ether
ETHER = arch/s370/ether/efaceinit.c	arch/s370/ether/ethmatch.c	 \
	arch/s370/ether/ethmcast.c	arch/s370/ether/getsim.c	 \
	arch/s370/ether/loopinit.c	arch/s370/ether/ofaceinit.c	 \
	arch/s370/ether/othinit.c	arch/s370/ether/othwrite.c	 \
	arch/s370/ether/pdump.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/ether
ETHEROBJ = ../build/obj/efaceinit.xsd	../build/obj/ethmatch.xsd	 \
	../build/obj/ethmcast.xsd	../build/obj/getsim.xsd	 \
	../build/obj/loopinit.xsd	../build/obj/ofaceinit.xsd	 \
	../build/obj/othinit.xsd	../build/obj/othwrite.xsd	 \
	../build/obj/pdump.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/global
GLOBAL = arch/s370/global/gbl_arp.c	arch/s370/global/gbl_clock.c	 \
	arch/s370/global/gbl_config.c	arch/s370/global/gbl_ctc.c	 \
	arch/s370/global/gbl_ether.c	arch/s370/global/gbl_igmp.c	 \
	arch/s370/global/gbl_ip.c	arch/s370/global/gbl_lock.c	 \
	arch/s370/global/gbl_mem.c	arch/s370/global/gbl_mvs.c	 \
	arch/s370/global/gbl_net.c	arch/s370/global/gbl_netif.c	 \
	arch/s370/global/gbl_proc.c	arch/s370/global/gbl_queue.c	 \
	arch/s370/global/gbl_sem.c	arch/s370/global/gbl_skel.c	 \
	arch/s370/global/gbl_snmp.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/global
GLOBALOBJ = ../build/obj/gbl_arp.xsd	../build/obj/gbl_clock.xsd	 \
	../build/obj/gbl_config.xsd	../build/obj/gbl_ctc.xsd	 \
	../build/obj/gbl_ether.xsd	../build/obj/gbl_igmp.xsd	 \
	../build/obj/gbl_ip.xsd	../build/obj/gbl_lock.xsd	 \
	../build/obj/gbl_mem.xsd	../build/obj/gbl_mvs.xsd	 \
	../build/obj/gbl_net.xsd	../build/obj/gbl_netif.xsd	 \
	../build/obj/gbl_proc.xsd	../build/obj/gbl_queue.xsd	 \
	../build/obj/gbl_sem.xsd	../build/obj/gbl_skel.xsd	 \
	../build/obj/gbl_snmp.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/kernel
KERNEL = arch/s370/kernel/doprnt.c	arch/s370/kernel/kprintf.c	 \
	arch/s370/kernel/main.c	arch/s370/kernel/panic.c	 \
	arch/s370/kernel/sysinit.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/kernel
KERNELOBJ = ../build/obj/doprnt.xsd	../build/obj/kprintf.xsd	 \
	../build/obj/main.xsd	../build/obj/panic.xsd	 \
	../build/obj/sysinit.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/memory
MEMORY = arch/s370/memory/freebuf.c	arch/s370/memory/freemem.c	 \
	arch/s370/memory/getbuf.c	arch/s370/memory/getmem.c	 \
	arch/s370/memory/getstk.c	arch/s370/memory/mark.c	 \
	arch/s370/memory/meminit.c	arch/s370/memory/memstate.c	 \
	arch/s370/memory/mkpool.c	arch/s370/memory/pcount.c	 \
	arch/s370/memory/pcreate.c	arch/s370/memory/pdelete.c	 \
	arch/s370/memory/pinit.c	arch/s370/memory/poolinit.c	 \
	arch/s370/memory/preceive.c	arch/s370/memory/preset.c	 \
	arch/s370/memory/psend.c	arch/s370/memory/ptclear.c	 \
	arch/s370/memory/receive.c	arch/s370/memory/recvclr.c	 \
	arch/s370/memory/recvtim.c	arch/s370/memory/send.c	 \
	arch/s370/memory/sendf.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/memory
MEMORYOBJ = ../build/obj/freebuf.xsd	../build/obj/freemem.xsd	 \
	../build/obj/getbuf.xsd	../build/obj/getmem.xsd	 \
	../build/obj/getstk.xsd	../build/obj/mark.xsd	 \
	../build/obj/meminit.xsd	../build/obj/memstate.xsd	 \
	../build/obj/mkpool.xsd	../build/obj/pcount.xsd	 \
	../build/obj/pcreate.xsd	../build/obj/pdelete.xsd	 \
	../build/obj/pinit.xsd	../build/obj/poolinit.xsd	 \
	../build/obj/preceive.xsd	../build/obj/preset.xsd	 \
	../build/obj/psend.xsd	../build/obj/ptclear.xsd	 \
	../build/obj/receive.xsd	../build/obj/recvclr.xsd	 \
	../build/obj/recvtim.xsd	../build/obj/send.xsd	 \
	../build/obj/sendf.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/mvs
MVS = arch/s370/mvs/comer_cksum.c	arch/s370/mvs/findsgd.c	 \
	arch/s370/mvs/findxgd.c	arch/s370/mvs/ibmcksum.c	 \
	arch/s370/mvs/ioslook.c	arch/s370/mvs/mvsabend.c	 \
	arch/s370/mvs/mvsenv.c	arch/s370/mvs/mvsintr.c	 \
	arch/s370/mvs/mvslock.c	arch/s370/mvs/mvsmem.c	 \
	arch/s370/mvs/mvsunlock.c	arch/s370/mvs/mvswto.c	 \
	arch/s370/mvs/snap.c	arch/s370/mvs/xconfig.c	 \
	arch/s370/mvs/xfig_gate.c	arch/s370/mvs/xfig_iface.c	 \
	arch/s370/mvs/xfig_prt.c	arch/s370/mvs/xfigger.c	 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/mvs
MVSOBJ = ../build/obj/comer_cksum.xsd	../build/obj/findsgd.xsd	 \
	../build/obj/findxgd.xsd	../build/obj/ibmcksum.xsd	 \
	../build/obj/ioslook.xsd	../build/obj/mvsabend.xsd	 \
	../build/obj/mvsenv.xsd	../build/obj/mvsintr.xsd	 \
	../build/obj/mvslock.xsd	../build/obj/mvsmem.xsd	 \
	../build/obj/mvsunlock.xsd	../build/obj/mvswto.xsd	 \
	../build/obj/snap.xsd	../build/obj/xconfig.xsd	 \
	../build/obj/xfig_gate.xsd	../build/obj/xfig_iface.xsd	 \
	../build/obj/xfig_prt.xsd	../build/obj/xfigger.xsd	 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/mvsasm
MVSASM = arch/s370/mvsasm/igc0024e.asm	arch/s370/mvsasm/igg019x8.asm	 \
	arch/s370/mvsasm/mvsclkinit.asm	arch/s370/mvsasm/mvsctc.asm	 \
	arch/s370/mvsasm/mvsdoze.asm	arch/s370/mvsasm/mvsevent.asm	 \
	arch/s370/mvsasm/mvswait.asm	arch/s370/mvsasm/mvswaitlist.asm	 \
	arch/s370/mvsasm/procload.asm	arch/s370/mvsasm/procsave.asm	 \
	arch/s370/mvsasm/procsw.asm	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/mvsasm
MVSASMOBJ = ../build/obj/igc0024e.xsd	../build/obj/igg019x8.xsd	 \
	../build/obj/mvsclkinit.xsd	../build/obj/mvsctc.xsd	 \
	../build/obj/mvsdoze.xsd	../build/obj/mvsevent.xsd	 \
	../build/obj/mvswait.xsd	../build/obj/mvswaitlist.xsd	 \
	../build/obj/procload.xsd	../build/obj/procsave.xsd	 \
	../build/obj/procsw.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/process
PROCESS = arch/s370/process/chprio.c	arch/s370/process/create.c	 \
	arch/s370/process/getpid.c	arch/s370/process/getprio.c	 \
	arch/s370/process/killpid.c	arch/s370/process/newpid.c	 \
	arch/s370/process/nulldisp.c	arch/s370/process/nullkill.c	 \
	arch/s370/process/nulluser.c	arch/s370/process/procinit.c	 \
	arch/s370/process/procstate.c	arch/s370/process/ready.c	 \
	arch/s370/process/resched.c	arch/s370/process/resume.c	 \
	arch/s370/process/sample.c	arch/s370/process/stackstate.c	 \
	arch/s370/process/suspend.c	arch/s370/process/userret.c	 \
	arch/s370/process/xdone.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/process
PROCESSOBJ = ../build/obj/chprio.xsd	../build/obj/create.xsd	 \
	../build/obj/getpid.xsd	../build/obj/getprio.xsd	 \
	../build/obj/killpid.xsd	../build/obj/newpid.xsd	 \
	../build/obj/nulldisp.xsd	../build/obj/nullkill.xsd	 \
	../build/obj/nulluser.xsd	../build/obj/procinit.xsd	 \
	../build/obj/procstate.xsd	../build/obj/ready.xsd	 \
	../build/obj/resched.xsd	../build/obj/resume.xsd	 \
	../build/obj/sample.xsd	../build/obj/stackstate.xsd	 \
	../build/obj/suspend.xsd	../build/obj/userret.xsd	 \
	../build/obj/xdone.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/queue
QUEUE = arch/s370/queue/dequeue.c	arch/s370/queue/enqueue.c	 \
	arch/s370/queue/getfirst.c	arch/s370/queue/getlast.c	 \
	arch/s370/queue/gpq.c	arch/s370/queue/insert.c	 \
	arch/s370/queue/newqueue.c	arch/s370/queue/queueinit.c	 \
	arch/s370/queue/queuestate.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/queue
QUEUEOBJ = ../build/obj/dequeue.xsd	../build/obj/enqueue.xsd	 \
	../build/obj/getfirst.xsd	../build/obj/getlast.xsd	 \
	../build/obj/gpq.xsd	../build/obj/insert.xsd	 \
	../build/obj/newqueue.xsd	../build/obj/queueinit.xsd	 \
	../build/obj/queuestate.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/sem
SEM = arch/s370/sem/newsem.c	arch/s370/sem/scount.c	 \
	arch/s370/sem/screate.c	arch/s370/sem/sdelete.c	 \
	arch/s370/sem/seminit.c	arch/s370/sem/signaln.c	 \
	arch/s370/sem/sreset.c	arch/s370/sem/wait.c	 \
	arch/s370/sem/xsignal.c	

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/sem
SEMOBJ = ../build/obj/newsem.xsd	../build/obj/scount.xsd	 \
	../build/obj/screate.xsd	../build/obj/sdelete.xsd	 \
	../build/obj/seminit.xsd	../build/obj/signaln.xsd	 \
	../build/obj/sreset.xsd	../build/obj/wait.xsd	 \
	../build/obj/xsignal.xsd	

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/stcp
STCP = 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/stcp
STCPOBJ = 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/temp
TEMP = 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/temp
TEMPOBJ = 

# mvs38j-geninc SOURCE definition for directory /herc2/mvs/ip/xinu/src/arch/s370/u370
U370 = 

# mvs38j-geninc OBJECT definition for directory /herc2/mvs/ip/xinu/src/arch/s370/u370
U370OBJ = 

