#
#  Makefile for the MVS38j version of Xinu to build compile/inc.mk
#

# Copy common macros into this Makefile
include ../build/macros.mk

GENINC = ${PERL}/mvs38j-genall

${INCMK}:
	${GENINC} ${SRCDIR}

